version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: ./front/Dockerfile.prod
    image: nginx-eth-img
    container_name: nginx-eth-ctn
    env_file:
      - ./env_files/front.env
    ports:
      - 8040:80
    #restart: always
    #変更する
    networks:
      - app_net_eth
    depends_on:
      - backend

  backend:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: ./back/Dockerfile.prod
    image: back-eth-img
    container_name: back-eth-ctn
    depends_on:
      mysql:
        condition: service_healthy
    expose:
      - 8001
    #変更する
    networks:
      - app_net_eth
    
  mysql:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    image: mysql-eth-img
    container_name: mysql-eth-ctn
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 1s
      retries: 10
      start_period: 3s
      timeout: 20s
    volumes:
      - ./mysql/db:/var/lib/mysql
    expose:
      - 3306
    env_file:
      - ./env_files/db.env
    #変更する
    networks:
      - app_net_eth

networks:
  app_net_eth:
    driver: bridge