version: "3"

services:
  front:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: ./front/Dockerfile.dev
    image: front-eth-dev-img
    container_name: front-eth-dev-ctn
    ports:
      - 8080:8080
    volumes:
      - ./front:/app/
    env_file:
      - ./env_files/front.env
    networks:
      - app_net_dev

  back:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: ./back/Dockerfile.dev
    image: back-eth-dev
    container_name: back-eth-dev
    ports:
      - 8001:8001
    expose:
      - 8001
    volumes:
      - ./back:/run/
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app_net_dev

  mysql:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    image: db-eth-dev-img
    container_name: db-eth-dev-ctn
    platform: linux/x86_64    # ← この設定を追加する
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 1s
      retries: 10
      start_period: 3s
      timeout: 20s
    volumes:
      - ./mysql/db:/var/lib/mysql
    expose:
      - 3306
    env_file:
      - ./env_files/db.env
    networks:
      - app_net_dev

networks:
  app_net_dev:
    driver: bridge