# Generated by Django 3.1 on 2022-09-02 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220902_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_group',
            field=models.BooleanField(null=True),
        ),
    ]
