FROM python:3.8

#pycファイルを生成しない
ENV PYTHONDONTWRITEBYTECODE 1
#バッファリングを行わない
ENV PYTHONUNBUFFERED 1

#作業ディレクトリを指定
WORKDIR /run

#必要なライブラリを記載したテキストファイルを作業ディレクトリへコピー
COPY ./back/requirements.txt /run
#pip[パッケージ管理ツール]を更新
RUN pip install --upgrade pip
#setuptoolsを更新
RUN pip install --upgrade setuptools
#ライブラリをインストール
RUN pip install -r requirements.txt

CMD ["sh", "entrypoint-back.sh"]