# ビルド環境
FROM node:14 as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY ./front .
RUN npm run build

# 本番環境
FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/dist /var/www/html
#nginx
COPY ./nginx/default.conf ./etc/nginx/conf.d/default.conf
#api
COPY ./nginx/uwsgi_params ./etc/nginx/uwsgi_params

#CMD ["nginx", "-g", "daemon off;"]